repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        exclude: |
            (?x)( # make whitespace in this regex insignificant and allow comments
                ^README.md|           # I use double-space line-endings a lot in my MD.
                resources/answers.py # MD also used in answers.
            )

- repo: https://github.com/patricknraanes/nbhooks.git
  rev: 1.2.0  # Set to the most recent version
  hooks:
  - id: nb-ensure-clean
    args: [--meta, pin_output]  # Optional WHITELIST of metadata keys (you can use regex)
